### ISSUE TITLE
iRODSResource needs access to its parent resource's name

### ISSUE THREAD

**Issue by tedgin** [irods/python-irodsclient#392]
I don't know if this is a bug report or a feature request.

In iRODS 4.1, for a given resource, the name of its parent was stored in the `resc_parent` column of the resource's entry in the `r_resc_main` table in the ICAT DB.  In 4.2, this entry was (sensibly) changed to holding the DB Id of the parent.  I suspect that the `iRODSResource` class in the python-irodsclient may not have been adjusted for this 4.2 change, because currently, the `parent` field holds the DB Id of the resource's parent.  I don't recall what it was with iRODS 4.1, but I suspect the `parent` field held the name of the parent. 

If I'm right, I would like to report a bug. 

If I'm wrong, I would like to make a feature request. Please add a method to `iRODSResource` that returns the name of the resource's parent resource. This would simplify navigating a resource hierarchy.

**Comment by trel** [comment]
I believe 4.1 probably *did* have the string name of the parent in that field.

I propose...

- `resc.parent` -> `id` as string -- same as today, no change, since people are probably already using it
- `resc.parent_id` -> `id` as integer -- same format as resc.id (already an integer)
- `resc.parent_name` -> `name` as string -- what you saw with `resc.parent` in 4.1

and then... perhaps also...

- `resc.hierarchy` and/or `resc.hier` -> semicolon-delimited string of hierarchy of this resource up to its root

maybe the last one is a separate issue/discussion...

**Comment by d-w-moore** [comment]
I'd be in favor of a resc.hierarchy as a @property instead of attribute ... that is, only calculated if referenced (and perhaps cached as a query-avoiding optimization for any use thereafter.)  That's basically because computing the hierarchy is N-1 queries for an N-deep resource.

**Comment by d-w-moore** [comment]
Same applies perhaps for other things like resc.parent* actually, though the cost is only 1 query in those cases.

**Comment by korydraughn** [comment]
Q. Should this always reflect the latest information or should it represent a snapshot in time?
Q. Wouldn't GenQuery make this a single lookup of `DATA_RESC_HIER`?
Q. Why cache the result? Caching the result could be the responsibility of the application rather than the `iRODSResource` type.

**Comment by d-w-moore** [comment]
A snapshot would be fine, as would leaving the caching  behavior to the application. It will be expensive however. 
And - my understanding of this issue is that it concerns reporting the  structure of the resource tree which will be expensive to do. To my knowledge DATA _RESC_HIER reflects the location of a DATA replica, so no, I think we'll be tracing the tree each time with 2 queries per upward Jump

**Comment by d-w-moore** [comment]
To calculate the resc.hier string of any node will require two queries per jump toward the root, so queries_per_node ends up being two times the distance from the root.  Each step requires (1) getting the resc ID of the parent and (2) based on that ID, querying for the various columns (including resc NAME) of that parent.

**Comment by d-w-moore** [comment]
But  expensive is relative, right?  I just meant it's more expensive than getting the DATA_RESC_HIER should a replica of something actually be stored on the resource. At least the upward tracing method is guaranteed to work though, independent of whether the resource  has any replicas.

**Comment by d-w-moore** [comment]
To see what I mean about the above, try comparing the results of
```
iquest "select RESC_DATA_HIER where RESC_NAME = 'myResc' "
```
 when a data replica exists on myResc vs. when no such replicas exist.

**Comment by korydraughn** [comment]
We could improve the situation by adding a specific query. Assuming we can write SQL that can resolve the parent resc_id and parent resc_name given a resource. That seems like a useful query.

**Comment by d-w-moore** [comment]
Alternatively we just make a free function in the Python library that computes a resc hierarchy given an iRODSResource object.  This makes it clearer to library users that retrieving the hierarchy string is not an iRODS innate capability, but  rather a client computation of O(Depth)

**Comment by d-w-moore** [comment]
We'll go that way for starters.  Other attributes like ID and name can be either properties (queried-for upon invocation) or attributes (set only upon instantiation).

**Comment by alanking** [comment]
@d-w-moore - Please close if complete. Thanks
