### ISSUE TITLE
data objects should properly finalize

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#456]
Consider the following script , append-dobj.py:

```
import irods.test.helpers as h
import sys
s = h.make_session()
PATH = sys.argv[1]
x = s.data_objects.open(PATH, 'a')
x.seek(0,2) # seek to end of file
x.write(b'\n')
```

If we run `./append-dobj.py `ipwd`/newfile` on iRODS >= 4.2.9,  after the script exits, the `newfile` replica thus produced has
  - "stale" status, despite being the only replica.
  - unchanged or zero content, depending on whether it existed previously.
 
On iRODS 4.2.8, although replicas are always given "good" status on process exit, the case is similar because "\n" does not get written.

This is all counter to the behavior for regular Linux / POSIX file objects.  So, for the iRODS case, apparently the onus is on the client to properly finalize data objects at process shutdown.

**Comment by trel** [comment]
I think after the server realizes that the client went away (and never said goodbye)… the server will close everything down and the data object will be okay.   Can you do another test and let it time out?  Then check the catalog and disk?

**Comment by korydraughn** [comment]
If the agent exits without crashing, the replica should be marked stale automatically.

Could the agent have crashed? That would result in the behavior reported.

**Comment by d-w-moore** [comment]
I've edited the problem statement to change "locked" to stale.

**Comment by d-w-moore** [comment]
To be even more clear ; ) ...
calling close( ) on the client's file descriptor before it goes out of scope (ie the client process exits) rectifies all of this.  
 That's essentially the difference I've introduced with #457. The close API automatically gets called on any dangling (still existing but not-as-yet closed) descriptors.

**Comment by korydraughn** [comment]
Given that you meant the replica is marked stale upon the script completing, the behavior you originally described is expected.

If the `close` operation isn't triggered, then you get a stale replica because the server cannot assume anything about what the client is attempting to do.

Your solution presented in #457 brings the PRC closer to how `dstream` works which may be a good thing. However, could this solution lead to incorrect results because the PRC would then always closes everything no matter what?

Perhaps the auto-closing functionality you're implementing should be a mechanism that people must opt into.

I don't necessary think that the issue raised is real. Developers should use `with` statements, etc to guarantee that data objects are closed appropriately. Or, they must be explicit about telling the PRC to auto-close everything.

**Comment by d-w-moore** [comment]
I agree with the opt-in, although the notion of no good replicas on client exit is a bit strange.

**Comment by trel** [comment]
> the notion of no good replicas on client exit is a bit strange

Agreed.   We should document the counter example that is more powerful than this case's sense of strangeness.

**Comment by d-w-moore** [comment]
>  We should document the counter example that is more powerful than this case's sense of strangeness.

Yes, although I can't think of any counterexample cases in which the auto-calling of close( ) on interpreter exit would be considered bad.  Unless there were competing Python interpreters running within the same process, vying for control over the same open file/object "descriptor".

**Comment by trel** [comment]
almost sounds like we leave the low level call as is.  No magic.   And consider an additional ‘easy button’ that cleans things up… but really, that would just be a ‘with’ statement… so… a documentation / best practices exercise it seems.

**Comment by korydraughn** [comment]
I agree.

I think the facility @d-w-moore has built is fine as long as it isn't the default behavior. We provide it for convenience and let the dev decide on whether it fits their use-case.

I vote we include @d-w-moore's work with tweaks so that it requires the dev to opt into it. Then we provide documentation explaining how to opt into it and use it correctly.

**Comment by d-w-moore** [comment]
Yes, I agree.  If that situation is best handled by opting-in to the auto-closing behavior, that's easy enough to put in.  I'm just saying I can't think of any plausible counterexamples for such an implementation, unless it's that the developer opts-in, but also sets up conditions in which __del__ doesn't get called. Which would be rare under standard CPython.

**Comment by trel** [comment]
Please close if complete.
