### ISSUE TITLE
Make PAM auth TTL customisable

### ISSUE THREAD

**Issue by sellth** [irods/python-irodsclient#494]
As I understand the current implementation, time-to-live for PAM auth tokens is hardcoded to 60. As we require longer lasting sessions for our use cases, it would be great if users could set TTL to a custom value within the constraints of the server's `pam_password_max_time` setting. The `iinit` command already implements this via the `--ttl` flag (https://docs.irods.org/4.3.1/icommands/user/#iinit).

For reference: https://github.com/irods/python-irodsclient/blob/96d2cd223cc9f755f3d12f72a99b600553e8d911/irods/connection.py#L438-L448

On a side note, I'm pretty sure that the default value of 60 is actually in hours and not seconds. So the variable is named wrongly in the code snippet above.

Reference of the server-side code: https://github.com/irods/irods/blob/aff93a3fbe417c8ec2e9d834b5eb2d6b2ae31083/lib/core/src/clientLogin.cpp#L237-L239

**Comment by d-w-moore** [comment]
I am not at all sure why the above code sends an AUTH_TTL_KEY value.  `_login_pam` is the function executed at the time of login, rather than the setting of such parameters as time-to-live, as with iinit.   In fact, the python-irodsclient does not innately contain any code that is the equivalent of iinit's function.
Having to do with 4.3.1, however - since @sellth mentioned it here - I'd like acknowledge another ongoing issue:  the need to teach PRC to go through the new (4.3.0+) pam_password implementation rather  than going through the legacy auth.

**Comment by sellth** [comment]
> I am not at all sure why the above code sends an AUTH_TTL_KEY value. _login_pam is the function executed at the time of login, rather than the setting of such parameters as time-to-live as is done by iinit. In fact, the python-irodsclient does not innately contain any code that is the equivalent of iinit's function.

It should define the TTL of *pam_pw_negotiated* which when saved "obfuscated" in the right place does provide `iinit` functionality.

https://github.com/irods/python-irodsclient/blob/96d2cd223cc9f755f3d12f72a99b600553e8d911/irods/session.py#L316-L323

**Comment by d-w-moore** [comment]
Ah, ok.  I see it now.

**Comment by alanking** [comment]
@d-w-moore - Please close if complete.
