### ISSUE TITLE
Document how to store passwords in `.irodsA` file

### ISSUE THREAD

**Issue by alanking** [irods/python-irodsclient#596]
It seems this is possible: https://github.com/irods/python-irodsclient/blob/067e63d1075d97d240f45a427495673aac5aaa07/irods/connection.py#L532-L536

However, this is not documented anywhere, and it's not clear (at least to me) whether this option is available outside of PAM authentication (this code is under `_pam_login`) or how to use it. Let's add documentation around how this works and how to use it.

**Comment by d-w-moore** [comment]
I think it's already documented [here](https://github.com/irods/python-irodsclient?tab=readme-ov-file#python-irods-client-settings-file) in the list item that describes the setting legacy_auth.pam.store_password_to_environment.  Do we need more detail in that section, or perhaps (more likely) elsewhere?

**Comment by alanking** [comment]
Oh, I see. I was not looking for that.

> This step is only performed while auto-renewing PAM authenticated sessions.

If this is true, that means that iRODS native authentication cannot use this feature. Is that true?

I feel like having a dedicated how-to section for this would be helpful. Or perhaps a mention of this option in the section about creating a connection (https://github.com/irods/python-irodsclient?tab=readme-ov-file#establishing-a-secure-connection) or one of the sections following that. Does that seem like a good idea? Maybe what we have is enough...

**Comment by korydraughn** [comment]
A new section makes sense given it wasn't obvious where to look.

That could be either a FAQ, Troubleshooting, or How-To section.

**Comment by d-w-moore** [comment]
> Oh, I see. I was not looking for that.
> 
> > This step is only performed while auto-renewing PAM authenticated sessions.
> 
> If this is true, that means that iRODS native authentication cannot use this feature. Is that true?
> 
> I feel like having a dedicated how-to section for this would be helpful. Or perhaps a mention of this option in the section about creating a connection (https://github.com/irods/python-irodsclient?tab=readme-ov-file#establishing-a-secure-connection) or one of the sections following that. Does that seem like a good idea? Maybe what we have is enough...

Native authentication doesn't execute this particular section of code , since it's located within _login_pam(), but yes, it does use the feature as such. That's to say, it stores password data in .irodsA implicitly.

It would be more accurate I guess to say: the PAM authentication in PRC needs explicit approval to overwrite .irodsA , and that approval is granted by setting `legacy_auth.pam.store_password_to_environment` to `True`.

This arose from trying to give the PRC some iinit-like behavior, which didn't have until a recent release.  Doing things this way made more sense than PRC shelling out to iinit whenever for example a PAM password was found to have expired.

Yes, it's true PRC has long had the capability of authenticating through PAM, but until that recent release it wasn't using stored .irodsA data, and persisting such data back into .irodsA for the next PAM session when the current password was found to have expired.  No, as I understand it, for a long time, PRC's handling of PAM was actually  authenticating each new session by generating the login tokens anew, via calling the PAM api, whereas the icommands' methodology was to decode the PAM token that existed already (in weakly encoded form) in `.irodsA`  .  So this just brings PRC up to where the iCommands have been.

**Comment by d-w-moore** [comment]
There's now a commit in pr  #620 documenting how users may employ PRC in place of `iinit` to store pam passwords. 

It isn't clear to me which route to go, in furnishing the `iinit`-like capability to create an .irodsA in PRC for native logins  as well.  Is that something we want / need ?   

If so, how do we prefer to proceed?
   - by using a similar configuration option, say legacy_auth.native.password, that enables writing the native .irodsA , or
   - by providing a free function in the PRC, something of this sort for anyone who wants to call it:
   ```
   def write_native_credentials( irods_password ):
      # open .irodsA path
      # write encoded irods_password
   ```

**Comment by korydraughn** [comment]
Providing a free function feels the most correct and enables flexibility.

I don't think the PRC should automatically write any files due to its design. That feels like a decision the user/dev should make. It's also not clear when the PRC would write that file.

**Comment by korydraughn** [comment]
Adding this as a discussion item.
