### ISSUE TITLE
error checks and limits on connection_timeout should happen at iRODSSession construction time

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#625]

**Comment by trel** [comment]
very similar / identical to #623

**Comment by alanking** [comment]
`connection_timeout` has its own setter method, so there is a slight distinction. Currently, there are no checks on the value set in the `__init__` method as passed in via the `kwargs` (either on the limit specified in #623, or negative values, or otherwise). @d-w-moore can of course correct me if I'm wrong there.

**Comment by d-w-moore** [comment]
> very similar / identical to #623

Yes.  In fact, this issue can be closed because it was addressed (though not attributed) in #624

**Comment by trel** [comment]
Closing.  Thanks.
